WebGallery/Controllers/AdministrationController.cs
using BLL.IdentityService;
using BLL.Services;
using Domain.Models;
using ExpressMapper.Extensions;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebGallery.Hubs;
using WebGallery.Models;

namespace WebGallery.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly UserManager<User, Guid> _userManager;
        private IUserStore _userStore;
        private IImageService _imageService;
        private ICommentService _commentService;

        public AdministrationController(UserManager<User, Guid> userManager, IUserStore userStore, IImageService imageService ,ICommentService commentService)
        {
            _userManager = userManager;
            _userStore = userStore;
            _imageService = imageService;
            _commentService = commentService;
        }

        public async Task<ActionResult> ControlUsers(int page = 1)
        {
            if (IsRight(moderator: "Moderator", admin: "Admin"))
            {
                var users = await GetUsersListByRole(page, "User");
                return View(users);
            }
            else
            {
                return View("NotRight");
            }
        }

        public ActionResult Create()
        {
            if (IsRight(moderator: "Moderator", admin: "Admin"))
            {
                ViewBag.Genres = _imageService.GetGenres(Guid.Empty);
                return View();
            }
            else
            {
                return View("NotRight");
            }
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload, ImageLoad imageLoad)
        {
            if (upload != null)
            {
                ImageDisplay imageDisplay = imageLoad.Map<ImageLoad, ImageDisplay>();
                imageDisplay.AuthorImageId = Guid.Parse(User.Identity.GetUserId());
                imageDisplay.Id = Guid.NewGuid();
                imageDisplay.DateTimeLoad = DateTime.Now;
                string extension = Path.GetExtension(upload.FileName);
                imageDisplay.Path = GetPath(imageDisplay.Id.ToString(), extension);
                upload.SaveAs(Server.MapPath(imageDisplay.Path));
                _imageService.Add(imageDisplay.Map<ImageDisplay, ImageDescript>());
                SendMessage(imageDisplay.Genre);
            }

            return RedirectToAction("Create");
        }
        
        public async Task<ActionResult> ImagesImgur()
        {
            ///Client-ID 41b4696307353f2
            List<ImageImgur> imageImgurs = new List<ImageImgur>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.TryAddWithoutValidation("Authorization", "Client-ID 41b4696307353f2");
                HttpResponseMessage response = await client.GetAsync("https://api.imgur.com/3/gallery/t/cat");
                response.EnsureSuccessStatusCode();
                var rbody = await response.Content.ReadAsAsync<RootObject>();

                imageImgurs = rbody.data.items.Where(t => t.images != null).SelectMany(p => p.images).ToList();
            }

            return View(imageImgurs);
        }
                       
        [HttpPost]
        public async Task<string> ToBan(string id)
        {
            var _id = Guid.Parse(id);
            var user = await _userStore.FindByIdAsync(_id);
            await _userStore.AddToRoleAsync(user, "Ban");
            await _userStore.RemoveFromRoleAsync(user, "User");
            return "200";
        }
        
        [HttpPost]
        public async Task<string> AddModerator(string id)
        {
            var _id = Guid.Parse(id);
            var user = await _userStore.FindByIdAsync(_id);
            await _userStore.AddToRoleAsync(user, "Moderator");
            await _userStore.RemoveFromRoleAsync(user, "User");
            return "200";
        }

        public async Task<ActionResult> ControlBanUsers(int page = 1)
        {
            if (IsRight(moderator: "Moderator", admin: "Admin"))
            {
                var users = await GetUsersListByRole(page, "Ban");
                return View(users);
            }
            else
            {
                return View("NotRight");
            }
        }

        [HttpPost]
        public async Task<string> RemoveBan(string id)
        {
            var _id = Guid.Parse(id);
            var user = await _userStore.FindByIdAsync(_id);
            await _userStore.RemoveFromRoleAsync(user, "Ban");
            await _userStore.AddToRoleAsync(user, "User");
            return "200";
        }

        public async Task<ActionResult> ControlModerators(int page = 1)
        {
            if (IsRight(admin: "Admin"))
            {
                var users = await GetUsersListByRole(page, "Moderator");
                return View(users);
            }
            else
            {
                return View("NotRight");
            }
        }
        
        [HttpPost]
        public async Task<string> RemoveModerator(string id)
        {
            var _id = Guid.Parse(id);
            var user = await _userStore.FindByIdAsync(_id);
            await _userStore.RemoveFromRoleAsync(user, "Moderator");
            await _userStore.AddToRoleAsync(user, "User");
            return "200";
        }

        public async Task<ActionResult> ModerationImage(int page = 1, string genre = null)
        {
            if (IsRight(moderator: "Moderator", admin: "Admin"))
            {
                var images = await GetImagesListByGenre(page, genre);
                return View(images); 
            }
            else
            {
                return View("NotRight");
            }
        }
        
        public async Task<ActionResult> EditImage(Guid id)
        {
            if (IsRight(moderator:"Moderator", admin: "Admin"))
            {
                return View((await _imageService.GetById(id)).Map<ImageDescript, ImageDisplay>());
            }
            else
            {
                return View("NotRight");
            }
        }

        [HttpPost]
        public async Task<string> RemoveImage(string id)
        {
            var _id = Guid.Parse(id);
            await _imageService.Remove(_id);
            return "200";
        }

        [HttpPost]
        public async Task<string> SaveDescript(string id, string description)
        {
            var _id = Guid.Parse(id);
            await _imageService.SaveDescript(_id, description);
            return "200";
        }

        public PartialViewResult PartialComment(Guid id, int page = 1)
        {
            return PartialView("PartialComment", GetCommentsList(id, page));
        }

        [HttpPost]
        public async Task<string> RemoveComment(string id)
        {
            var _id = Guid.Parse(id);
            await _commentService.Remove(_id);
            return "200";
        }

        public PartialViewResult PartialViewModerator()
        {
            var _Id= Guid.Parse(User.Identity.GetUserId());
            var roles = _userStore.GetRolesbyId(_Id);
            if (roles.Any(r=>r.Name=="Ban"))
            {
                return PartialView("PartialViewEmpty");
            }
            else if (roles.Any(r => r.Name == "Moderator" | r.Name == "Admin"))
            {
                return PartialView("PartialViewModerator");
            }
            return PartialView("PartialViewEmpty");
        }

        public PartialViewResult PartialViewAdmin()
        {
            var _Id = Guid.Parse(User.Identity.GetUserId());
            var roles = _userStore.GetRolesbyId(_Id);
            if (roles.Any(r => r.Name == "Ban"))
            {
                return PartialView("PartialViewEmpty");
            }
            else if (roles.Any(r => r.Name == "Admin"))
            {
                return PartialView("PartialViewAdmin");
            }
            return PartialView("PartialViewEmpty");
        }

        private bool IsRight(string moderator= "NotModerator",string admin= "NotAdmin")
        {
            var _Id = Guid.Parse(User.Identity.GetUserId());
            var roles = _userStore.GetRolesbyId(_Id);
            if (roles.Any(r => r.Name == moderator || r.Name == admin))
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        private async Task<ImageListDisplay> GetImagesListByGenre(int page = 1, string genre = null)
        {
            int take = 40;
            int skip = (page - 1) * take;
            var images = (await _imageService.GetByGenre(genre, take, skip)).Map<IEnumerable<ImageDescript>, IEnumerable<ImageDisplay>>();
            var count = await _imageService.CountImagesInGenre(genre);

            var imageslist = new ImageListDisplay
            {
                CurrentGenre = genre,
                Images = images,
                Page = new PageInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = take,
                    TotalItems = count,
                },
            };
            return imageslist;
        }

        private async Task<UsersList> GetUsersListByRole(int page, string role)
        {
            int take = 40;
            int skip = (page - 1) * take;
            var users = _userStore.GetUsersByRole(skip, take, role);
            var count = await _userStore.CountUsersByRole(role);
            var usersList = new UsersList
            {
                Users = users,
                MaxPage = (count % take) == 0 ? count / take : count / take + 1,
                Page = page,
            };
            return usersList;
        }

WebGallery/Views/Administration/ControlBanUsers.cshtml
@model WebGallery.Models.UsersList


<div class="gallery">
    <div class="images-line">
        <div class="img-rack">

            @foreach (var user in Model.Users)
            {
                <div class="Users_control">
                    <div class="Users_control_b0">
                        @user.UserName
                    </div>
                    <div class="Users_control_b1" idbtn="@user.Id">
                        <input type="button" value="Разбанить" onclick="RemoveBan('@user.Id.ToString()')" />
                    </div>
                </div>
                <hr />
            }

            <hr />
            <div style="width: 100%;">
                @{
                    var next = Model.Page + 1;
                    var previous = Model.Page - 1;
                    if (Model.Page == 1 && Model.MaxPage > 1)
                    {
                        <a href="Administration/ControlBanUsers?page=@next" class="toRight">Cледующие</a>
                    }
                    else if (Model.Page == Model.MaxPage && Model.MaxPage > 1)
                    {
                        <a href="Administration/ControlBanUsers?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                    }
                    else if (Model.Page > 1 && Model.MaxPage < Model.MaxPage)
                    {
                        <a href="Administration/ControlBanUsers?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                        <a href="Administration/ControlBanUsers?page=@next" class="toRight">Cледующие</a>
                    }
                }
            </div>
        </div>
    </div>
</div>

WebGallery/Views/Administration/ControlModerators.cshtml
@model WebGallery.Models.UsersList


<div class="gallery">
    <div class="images-line">
        <div class="img-rack">

            @foreach (var user in Model.Users)
            {
                <div class="Users_control">
                    <div class="Users_control_b0">
                        @user.UserName
                    </div>
                    <div class="Users_control_b1" idbtn="@user.Id">
                        <input type="button"  value="Снять права модератора" onclick="RemoveModerator('@user.Id.ToString()')" />
                    </div>
                </div>
                <hr />
            }

            <hr />
            <div style="width: 100%;">
                @{
                    var next = Model.Page + 1;
                    var previous = Model.Page - 1;
                    if (Model.Page == 1 && Model.MaxPage > 1)
                    {
                        <a href="Administration/ControlModerators?page=@next" class="toRight">Cледующие</a>
                    }
                    else if (Model.Page == Model.MaxPage && Model.MaxPage > 1)
                    {
                        <a href="Administration/ControlModerators?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                    }
                    else if (Model.Page > 1 && Model.MaxPage < Model.MaxPage)
                    {
                        <a href="Administration/ControlModerators?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                        <a href="Administration/ControlModerators?page=@next" class="toRight">Cледующие</a>
                    }
                }
            </div>
        </div>
    </div>
</div>

WebGallery/Views/Administration/ControlUsers.cshtml
@model WebGallery.Models.UsersList


<div class="gallery">
    <div class="images-line">
        <div class="img-rack">

            @foreach (var user in Model.Users)
            {
                <div class="Users_control">
                    <div class="Users_control_b0">
                        @user.UserName
                    </div>
                    <div class="Users_control_b1" idbtn="@user.Id">
                        <span>
                            <input type="button"  value="Дать Бан" onclick="ToBan('@user.Id.ToString()')" />
                        </span>
                        <span>
                            <input type="button"  value="Дать модератора" onclick="AddModerator('@user.Id.ToString()')" />
                        </span>
                    </div>
                </div>
                <hr class="line" />
            }

            <hr />
            <div style="width: 100%;">
                @{
                    var next = Model.Page + 1;
                    var previous = Model.Page - 1;
                    if (Model.Page == 1 && Model.MaxPage > 1)
                    {
                        <a href="Administration/ControlUsers?page=@next" class="toRight">Cледующие</a>
                    }
                    else if (Model.Page == Model.MaxPage && Model.MaxPage > 1)
                    {
                        <a href="Administration/ControlUsers?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                    }
                    else if (Model.Page > 1 && Model.MaxPage < Model.MaxPage)
                    {
                        <a href="Administration/ControlUsers?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                        <a href="Administration/ControlUsers?page=@next" class="toRight">Cледующие</a>
                    }
                }
            </div>
        </div>
    </div>
</div>

WebGallery/Views/Administration/Create.cshtml
@model WebGallery.Models.ImageLoad

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/Create.js"></script>
<form action="/Administration/Upload" method="post" id="CreateForm" enctype="multipart/form-data">
    <table class="LoadImage">
        <tr>
            <td>
                <label>Название</label>
            </td>
            <td>
                <div>
                    <input id="Name" name="Name" type="text" value="" class="tdInput" />
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label>Загрузите Ваше изображение</label>
            </td>
            <td>
                <div>
                    <input type="file" name="upload" accept="image/*,image/jpeg" class="tdInput" id="file-input">
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label>Выбрать жанр</label>
            </td>
            <td>
                <div>
                    <select id="Genre1" name="Genre" class="tdInput">
                        @foreach (var genre in ViewBag.Genres)
                        {
                            <option value="@genre.Genre">@genre.Genre</option>
                        }
                    </select>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label>Или укажите новый жанр </label>
                <input type="checkbox" id="checker" value="новый жанр" onclick="activOn(this)" />
            </td>
            <td>
                <div>
                    <input id="Genre2" name="Genre" type="text" value="" disabled="disabled" class="tdInput" />
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <label>Дайте короткий комментарий</label>
            </td>
            <td>
                <div>
                    <textarea id="Description" name="Description" class="textarea"></textarea>
                </div>
            </td>
        </tr>
    </table>
    <div><input type="checkbox" id="IsPrivate" name="IsPrivate" />Изображение только для зарегистрированных пользователей</div>


    <div id="list-view"></div>
    <div class="upload_button">
        <input type="submit" value="Загрузить" id="Create" />
    </div>
</form>

WebGallery/Views/Administration/EditImage.cshtml
@model WebGallery.Models.ImageDisplay

<div class="login_container">
    <div class="shadow_container">
        <a class="back_button" href="javascript:history.back()"><i class="fas fa-times"></i></a>
        <div class="Image-str" id="@Model.Id">
            <div class="Image-name">@Model.Name</div>
            <div>
                <img src="@Url.Content(Model.Path)" alt="картинка" width="800" />
            </div>
            <div>
                <div class="like_zone">
                    <a class="like" idimage="@Model.Id">
                        <i class="far fa-thumbs-up"></i>
                        <i likeidimage="@Model.Id">@Model.Like</i>
                    </a>
                    <a class="dislike" idimage="@Model.Id">
                        <i class="far fa-thumbs-down"></i>
                        <i dislikeidimage="@Model.Id">@Model.DisLike</i>
                    </a>
                    <span class="TimeLoad">
                        @Model.DateTimeLoad.ToString("U")
                    </span>
                </div>
            </div>
            <textarea id="DescriptionIMG" class="Image-description" disabled="disabled">@Model.Description</textarea>
            <input type="button" id="btnEditDescript" value="Редактировать"  onclick="EditDiscript()"/>
            <input type="button" id="btnSaveDescript" value="Сохранить" disabled="disabled" onclick="SaveDescript('@Model.Id.ToString()')" />
        </div>

        <div class="comments_container">

            @{
                Html.RenderAction("PartialComment", "Administration", new { id = Model.Id });
            }
        </div>
    </div>
</div>

WebGallery/Views/Administration/ImagesImgur.cshtml
@model IEnumerable<ImageImgur>

@{
    ViewBag.Title = "ImagesImgur";
}

<h2>ImagesImgur</h2>


<div class="gallery">
            <div class="images-line">
                <div class="img-rack">
                    @{
                        foreach (var image in Model)
                        {
                            <div class="img-slid">
                                <figure>                                 
                                        <img src="@image.link" alt="image_name">

                                    <figcaption>
                                        <div class="img_name">@image.description</div>
                                    </figcaption>
                                </figure>
                            </div>
                        }
                    }
                </div>
            </div>
        }

    }
</div>

WebGallery/Views/Administration/ModerationImage.cshtml
@model WebGallery.Models.ImageListDisplay

<div class="list_group">
    <div class="list_line">
        <div class="list_item10">
            Имя
        </div>

        <div class="list_item10">
            Жанр
        </div>

        <div class="list_item40">
            Описание
        </div>

        <div class="list_item5">
            Like
        </div>
        <div class="list_item5">
            DisLike
        </div>
    </div>
    <hr class="line" />

    @foreach (var item in Model.Images)
    {
        <div class="list_line" idbtn="@item.Id">
            <div class="list_item10">
                <a href="/Administration/EditImage?id=@item.Id"> @item.Name &nbsp; &nbsp; </a>
            </div>

            <div class="list_item10">
                @Html.DisplayFor(modelItem => item.Genre)  &nbsp;
            </div>
            <div class="list_item40">
                @Html.DisplayFor(modelItem => item.Description)  &nbsp;
            </div>

            <div class="list_item5">
                @Html.DisplayFor(modelItem => item.Like)  &nbsp;
            </div>
            <div class="list_item5">
                @Html.DisplayFor(modelItem => item.DisLike)   &nbsp;
            </div>
            <div class="list_item30">
                <input type="button"  value="Удалить" onclick="DelImg('@item.Id.ToString()')" />
            </div>
        </div>
        <hr class="line" />
    }
</div>

WebGallery/Views/Administration/NotRight.cshtml
<div class="login_container">
    <div class="shadow_container">
        <a class="back_button" href="javascript:history.back()"><i class="fas fa-times"></i></a>
        <div class="NotRight">
            Нет Прав!!!
        </div>
    </div>
</div>

WebGallery/Views/Administration/PartialComment.cshtml
@model WebGallery.Models.CommentsList

<div class="comments_zone" id="coments">
    @foreach (var item in Model.Comments)
    {
        <div idbtn="@item.Id">
            <div class="toLeft">
                @item.WriterName
            </div>
            <div class="toRight">
                @item.DateTimeComment.ToString("U")
            </div>
            <br />
            <div>
                @item.CommentContent
            </div>
            <div>
                <input type="button" value="Удалить" onclick="DelComment('@item.Id.ToString()')" />
            </div>
            <br />
        </div>
    }
    <div>
        @{
            if (Model.Page == 1 && Model.MaxPage > 1)
            {
                <a href="" id="next" onclick="nextpageA(event)" class="toRight">Cледующие</a>
            }
            else if (Model.Page == Model.MaxPage && Model.MaxPage > 1)
            {
                <a href="" id="previous" onclick="previoupageA(event)" class="toLeft">Предыдущие &nbsp;</a>
            }
            else if (Model.Page > 1 && Model.Page < Model.MaxPage)
            {
                <a href="" id="previous" onclick="previoupageA(event)" class="toLeft">Предыдущие &nbsp;</a><a href="" id="next" onclick="nextpageA(event)" class="toRight">Cледующие</a>
            }
        }
    </div>
</div>
<div>
    <form id="CommentsList">
        <input type="hidden" id="CarentPage" name="Page" value="@Model.Page" />
        <input type="hidden" name="ImageId" value="@Model.ImageId" />
    </form>
</div>

WebGallery/Views/Administration/PartialViewAdmin.cshtml
<li><a href="/Administration/ControlModerators"> Управление модераторами</a></li>

WebGallery/Views/Administration/PartialViewModerator.cshtml
<li><a href="/Administration/Create">Загрузить</a></li>
<li><a href="/Administration/ImagesImgur">ImagesImgur(Cats)</a></li>
<li><a href="/Administration/ModerationImage">Редактирование изображений</a></li>
<li><a href="/Administration/ControlUsers"> Управление пользователями</a></li>
<li><a href="/Administration/ControlBanUsers"> Забаненые пользователи</a></li>