WebGallery/Controllers/ImageController.cs
using BLL.IdentityService;
using BLL.Services;
using BLL.ServicesFactory;
using DAL.Entities;
using Domain.Models;
using ExpressMapper.Extensions;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebGallery.Models;

namespace WebGallery.Controllers
{
    public class ImageController : Controller
    {
        UserManager<User,Guid> _userManager;
        IImageService _imageService;
        ICommentService _commentService;
        IUserStore _userStore;
        public ImageController(IImageService imageService, ICommentService commentService, UserManager<User, Guid> userManager ,IUserStore userStore)
        {
            _imageService = imageService;
            _commentService = commentService;
            _userManager = userManager;
            _userStore = userStore;
        }
               
        public async Task<ActionResult> Index(string genre = null, int page = 1)
        {

            if (genre != null)
            {
                PageInfo pageInfo = new PageInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = 20,
                    TotalItems = await _imageService.CountImagesInGenre(genre),
                    
                };
                ImageListDisplay imageList = new ImageListDisplay()
                {
                    CurrentGenre = genre,
                    Page = pageInfo,
                    Images = (await _imageService.GetByGenre(genre, pageInfo.ItemsPerPage, pageInfo.SkipItems))
                                                 .Map<IEnumerable<ImageDescript>, IEnumerable<ImageDisplay>>(),
                };
                return View(imageList);
            }
            return View("ViewStart");
        }

        public PartialViewResult PartialViewMenu()
        {
            Guid idUser = Guid.Empty;
            if (Request.IsAuthenticated)
            {
                idUser = Guid.Parse(User.Identity.GetUserId());
            }
            var resault = _imageService.GetGenres(idUser);
            return PartialView("PartialViewMenu", resault.Map<IEnumerable<GenreImage>, IEnumerable<GenreDisplay>>());
        }

        public PartialViewResult PartialViewGenry()
        {
            var resault = _imageService.GetGenres(Guid.Empty);
            return PartialView("PartialViewGenry", resault.Map<IEnumerable<GenreImage>, IEnumerable<GenreDisplay>>());
        }

        public PartialViewResult PartialViewAll()
        {
            Guid idUser = Guid.Empty;
            if (Request.IsAuthenticated)
            {
                idUser = Guid.Parse(User.Identity.GetUserId());
            }
            var _images = _imageService.GetImgOfStartPage(idUser);

            return PartialView("PartialViewAll", _images.Map<List<ImgOfStartPage<ImageDescript>>, List<StartPageDispay<ImageDisplay>>>());
        }

        public ActionResult ImageAllGenry()
        {
            var _images = _imageService.GetImgOfStartPage(Guid.Empty);

            return View("ImageAllGenry", _images.Map<List<ImgOfStartPage<ImageDescript>>, List<StartPageDispay<ImageDisplay>>>());
        }


        public PartialViewResult PartialComment(Guid id, int page=1)
        {
            return PartialView("PartialComment", GetCommentsList(id, page));
        }

        [HttpGet]
        public JsonResult Comments(string id, int page = 1)
        {
            var _id = Guid.Parse(id);
            var comments = GetCommentsList(_id, page);
            return Json(comments, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Details(Guid id)
        {
            return View((await _imageService.GetById(id)).Map<ImageDescript, ImageDisplay>());
        }

        [HttpPost]
        public async Task<JsonResult> Find(string Search)
        {
            var images = (await _imageService.Find(Search, 10)).Select(p => new { p.Name, p.Path, p.Id });
            return Json(images, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> FindPage(string search, int page = 1)
        {
            if (search != null | search != "")
            {
                PageInfo pageInfo = new PageInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = 20,
                    TotalItems = await _imageService.CountImgFind(search),
                };
                FindListDisplay findList = new FindListDisplay()
                {
                    Search = search,
                    Page = pageInfo,
                    Images = (await _imageService.Find(search, pageInfo.ItemsPerPage, pageInfo.SkipItems))
                                                 .Map<IEnumerable<ImageDescript>, IEnumerable<ImageDisplay>>(),
                };
                return View(findList);
            }
            return View("ViewStart");
        }

        public async Task<ActionResult> PopularImages(int page = 1)
        {

            PageInfo pageInfo = new PageInfo()
            {
                CurrentPage = page,
                ItemsPerPage = 20,
                TotalItems = await _imageService.CountImage(),
            };
            SortListDisplay imageList = new SortListDisplay()
            {

                Page = pageInfo,
                Images = (await _imageService.PopularImage( pageInfo.ItemsPerPage, pageInfo.SkipItems))
                                             .Map<IEnumerable<ImageDescript>, IEnumerable<ImageDisplay>>(),
            };
            return View(imageList);
        }

        public async Task<ActionResult> NewImages(int page = 1)
        {
            var oneDayAgo = DateTime.Now.AddDays(-1.01);
            PageInfo pageInfo = new PageInfo()
            {
                CurrentPage = page,
                ItemsPerPage = 20,
                TotalItems = await _imageService.CountSortImage(p => p.DateTimeLoad > oneDayAgo),
            };
            SortListDisplay imageList = new SortListDisplay()
            {
                Page = pageInfo,
                Images = (await _imageService.SortImage(p => p.DateTimeLoad > oneDayAgo, pageInfo.ItemsPerPage, pageInfo.SkipItems))
                                             .Map<IEnumerable<ImageDescript>, IEnumerable<ImageDisplay>>(),
            };
            return View(imageList);
        }

        public PartialViewResult PartialCommentForm(Guid id)
        {
            var _Id = Guid.Parse(User.Identity.GetUserId());
            var roles = _userStore.GetRolesbyId(_Id);
            if (roles.Any(r => r.Name == "Ban"))
            {
                return PartialView("PartialViewEmpty");
            }
            return PartialView("PartialCommentForm", id);
        }

        private CommentsList GetCommentsList(Guid id, int page = 1)
        {
            int take = 10;
            int skip = (page - 1) * take;
            var comments = _commentService.GetComments(id, take, skip);
            var commentsList = new CommentsList();
            commentsList.Comments = comments.Map<List<Comment>, List<CommentDisplay>>();
            commentsList.ImageId = id;
            var countComments = _commentService.CountComments(id);
            commentsList.MaxPage = (countComments % take) == 0 ? countComments / take : countComments / take + 1;
            commentsList.Page = page;
            return commentsList;
        }
    }
}

WebGallery/Views/Image/Details.cshtml
@model WebGallery.Models.ImageDisplay

<div class="login_container">
    <div class="shadow_container">
        <a class="back_button" href="javascript:history.back()"><i class="fas fa-times"></i></a>
        <div class="Image-str" id="@Model.Id">
            <div class="Image-name">@Model.Name</div>
            <div>
                <img src="@Url.Content(Model.Path)" alt="картинка" width="800" />
            </div>
            <div>
                <div class="like_zone">
                    <a class="like" idimage="@Model.Id">
                        <i class="far fa-thumbs-up"></i>
                        <i likeidimage="@Model.Id">@Model.Like</i>
                    </a>
                    <a class="dislike" idimage="@Model.Id">
                        <i class="far fa-thumbs-down"></i>
                        <i dislikeidimage="@Model.Id">@Model.DisLike</i>
                    </a>
                    <span class="TimeLoad">
                        @Model.DateTimeLoad.ToString("U")
                    </span>
                </div>
            </div>
            <div class="Image-description">@Model.Description</div>
        </div>

        <div class="comments_container">
            @if (User.Identity.IsAuthenticated)
            {
                Html.RenderAction("PartialCommentForm", "Image", new { id = Model.Id });
            }
            @{
                Html.RenderAction("PartialComment", "Image", new { id = Model.Id });
            }
        </div>
    </div>
</div>

WebGallery/Views/Image/FindPage.cshtml
@model WebGallery.Models.FindListDisplay

<div class="gallery">
    <div class="images-line">
        <div class="img-title">
            По запросу &nbsp; @Model.Search &nbsp; найдено:
        </div>
        <div class="img-rack">
            @{
                foreach (var image in Model.Images)
                {
                    <div class="img-slid" id="@image.Id">
                        <figure>
                            <a href="@Url.Action("Details", "Image", new { id = image.Id })" class="increase_link">
                                <img src="@Url.Content(image.Path)" alt="image_name">
                            </a>
                            <figcaption>
                                <div>@image.Name</div>
                                <div>
                                    <a class="like" idimage="@image.Id">
                                        <i class="far fa-thumbs-up"></i>
                                        <i likeidimage="@image.Id">@image.Like</i>
                                    </a>
                                    <a class="dislike" idimage="@image.Id">
                                        <i class="far fa-thumbs-down"></i>
                                        <i dislikeidimage="@image.Id">@image.DisLike</i>
                                    </a>
                                </div>
                            </figcaption>
                        </figure>
                    </div>
                }
            }
        </div>
        <div>
            @{
                var next = Model.Page.CurrentPage + 1;
                var previous = Model.Page.CurrentPage - 1;
                if (Model.Page.CurrentPage == 1 && Model.Page.TotalPages > 1)
                {
                    <a href="/Image/FindPage?search=@Model.Search&&page=@next" class="toRight">Cледующие</a>
                }
                else if (Model.Page.CurrentPage == Model.Page.TotalPages && Model.Page.TotalPages > 1)
                {
                    <a href="/Image/FindPage?search=@Model.Search&&page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                }
                else if (Model.Page.CurrentPage > 1 && Model.Page.CurrentPage < Model.Page.TotalPages)
                {
                    <a href="/Image/FindPage?search=@Model.Search&&page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                    <a href="/Image/FindPage?search=@Model.Search&&page=@next" class="toRight">Cледующие</a>
                }
            }
        </div>
    </div>
</div>

WebGallery/Views/Image/ImageAllGenry.cshtml
@using WebGallery.Models
@model  IEnumerable<StartPageDispay<ImageDisplay>>
<div class="gallery">
    @{ foreach (var imagescol in Model)
        {
            <div class="images-line">
                <div class="img-title">
                    @imagescol.Genre
                </div>
                <div class="img-rack">
                    @{
                        foreach (var image in imagescol.Images)
                        {
                            <div class="img-slid" id="@image.Id">
                                <figure>
                                    <a href="@Url.Action("Details", "Image", new { id = image.Id })" class="increase_link">
                                        <img src="@Url.Content(image.Path)" alt="image_name">
                                    </a>
                                    <figcaption>
                                        <div class="img_name">@image.Name</div>
                                        <div>
                                            <a class="like" idimage="@image.Id">
                                                <i class="far fa-thumbs-up likedislike"></i>
                                                <i likeidimage="@image.Id">@image.Like</i>
                                            </a>
                                            <a class="dislike" idimage="@image.Id">
                                                <i class="far fa-thumbs-down likedislike"></i>
                                                <i dislikeidimage="@image.Id">@image.DisLike</i>
                                            </a>
                                        </div>
                                    </figcaption>
                                </figure>
                            </div>
                        }
                    }
                </div>
            </div>
        }

    }
</div>

WebGallery/Views/Image/Index.cshtml
@using WebGallery.Models
@model ImageListDisplay


<div class="gallery">
    <div class="images-line">
        <div class="img-title">
            @Model.CurrentGenre
        </div>
        <div class="img-rack">
            @{
                foreach (var image in Model.Images)
                {
                    <div class="img-slid" id="@image.Id">
                        <figure>
                            <a href="@Url.Action("Details", "Image", new { id = image.Id })" class="increase_link">
                                <img src="@Url.Content(image.Path)" alt="image_name">
                            </a>
                            <figcaption>
                                <div>@image.Name</div>
                                <div>
                                    <a class="like" idimage="@image.Id">
                                        <i class="far fa-thumbs-up"></i>
                                        <i likeidimage="@image.Id">@image.Like</i>
                                    </a>
                                    <a class="dislike" idimage="@image.Id">
                                        <i class="far fa-thumbs-down"></i>
                                        <i dislikeidimage="@image.Id">@image.DisLike</i>
                                    </a>
                                </div>
                            </figcaption>
                        </figure>
                    </div>
                }
            }
        <hr />
            <div style="width: 100%;">
                @{
                    var next = Model.Page.CurrentPage + 1;
                    var previous = Model.Page.CurrentPage - 1;
                    if (Model.Page.CurrentPage == 1 && Model.Page.TotalPages > 1)
                    {
                        <a href="/Image/Index?genre=@Model.CurrentGenre&&page=@next" class="toRight">Cледующие</a>
                    }
                    else if (Model.Page.CurrentPage == Model.Page.TotalPages && Model.Page.TotalPages > 1)
                    {
                        <a href="/Image/Index?genre=@Model.CurrentGenre&&page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                    }
                    else if (Model.Page.CurrentPage > 1 && Model.Page.CurrentPage < Model.Page.TotalPages)
                    {
                        <a href="/Image/Index?genre=@Model.CurrentGenre&&page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                        <a href="/Image/Index?genre=@Model.CurrentGenre&&page=@next" class="toRight">Cледующие</a>
                    }
                }
            </div>
        </div>
    </div>
</div>

WebGallery/Views/Image/NewImages.cshtml
@model WebGallery.Models.SortListDisplay

<div class="gallery">
    <div class="images-line">
        <div class="img-rack">
            @{
                foreach (var image in Model.Images)
                {
                    <div class="img-slid" id="@image.Id">
                        <figure>
                            <a href="@Url.Action("Details", "Image", new { id = image.Id })" class="increase_link">
                                <img src="@Url.Content(image.Path)" alt="image_name">
                            </a>
                            <figcaption>
                                <div>@image.Name</div>
                                <div>
                                    <a class="like" idimage="@image.Id">
                                        <i class="far fa-thumbs-up"></i>
                                        <i likeidimage="@image.Id">@image.Like</i>
                                    </a>
                                    <a class="dislike" idimage="@image.Id">
                                        <i class="far fa-thumbs-down"></i>
                                        <i dislikeidimage="@image.Id">@image.DisLike</i>
                                    </a>
                                </div>
                            </figcaption>
                        </figure>
                    </div>
                }
            }
        </div>
        <div>
            @{
                var next = Model.Page.CurrentPage + 1;
                var previous = Model.Page.CurrentPage - 1;
                if (Model.Page.CurrentPage == 1 && Model.Page.TotalPages > 1)
                {
                    <a href="/Image/NewImages?page=@next" class="toRight">Cледующие</a>
                }
                else if (Model.Page.CurrentPage == Model.Page.TotalPages && Model.Page.TotalPages > 1)
                {
                    <a href="/Image/NewImages?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                }
                else if (Model.Page.CurrentPage > 1 && Model.Page.CurrentPage < Model.Page.TotalPages)
                {
                    <a href="/Image/NewImages?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                    <a href="/Image/NewImages?page=@next" class="toRight">Cледующие</a>
                }
            }
        </div>
    </div>
</div>

WebGallery/Views/Image/PartialComment.cshtml
@model WebGallery.Models.CommentsList

<div class="comments_zone" id="coments">
    @foreach (var item in Model.Comments)
    {
        <div>
            <div class="toLeft">
                @item.WriterName
            </div>
            <div class="toRight">
                @item.DateTimeComment.ToString("U")
            </div>
            <br />
            <div>
                @item.CommentContent
            </div>
            <br />
        </div>
    }
        <div>
            @{
                if (Model.Page == 1 && Model.MaxPage>1)
                {
                    <a href="" id="next" onclick="nextpage(event)" class="toRight">Cледующие</a>
                }
                else if (Model.Page == Model.MaxPage && Model.MaxPage>1)
                {
                    <a href="" id="previous" onclick="previoupage(event)" class="toLeft">Предыдущие &nbsp;</a>
                }
                else if (Model.Page > 1 && Model.Page < Model.MaxPage)
                {
                    <a href="" id="previous" onclick="previoupage(event)" class="toLeft">Предыдущие &nbsp;</a><a href="" id="next" onclick="nextpage(event)" class="toRight">Cледующие</a>
                }
            }
        </div>
</div>
<div>
    <form id="CommentsList">
        <input type="hidden" id="CarentPage" name="Page" value="@Model.Page" />
        <input type="hidden" name="ImageId" value="@Model.ImageId" />
    </form>
</div>

WebGallery/Views/Image/PartialCommentForm.cshtml
@model Guid

<form id="CreateComment">
    <input type="hidden" name="WriterId" value="@User.Identity.GetUserId()" />
    <input type="hidden" name="WriterName" value="@User.Identity.GetUserName()" />
    <input type="hidden" name="ImageId" value="@Model" />
    <textarea name="CommentContent" id="CommentText"></textarea>
    <input type="button" id="btnCreateComment" value="Отправить" />
</form>

WebGallery/Views/Image/PartialViewAll.cshtml
@using WebGallery.Models
@model  IEnumerable<StartPageDispay<ImageDisplay>>
<div class="gallery">
    @{ foreach (var imagescol in Model)
        {
            <div class="images-line">
                <div class="img-title">
                    @imagescol.Genre
                </div>
                <div class="img-rack">
                    @{
                        foreach (var image in imagescol.Images)
                        {
                            <div class="img-slid" id="@image.Id">
                                <figure>
                                    <a href="@Url.Action("Details", "Image", new { id = image.Id })" class="increase_link">
                                        <img src="@Url.Content(image.Path)" alt="image_name">
                                    </a>
                                    <figcaption>
                                        <div class="img_name">@image.Name</div>
                                        <div>
                                            <a class="like" idimage="@image.Id">
                                                <i class="far fa-thumbs-up likedislike"></i>
                                                <i likeidimage="@image.Id">@image.Like</i>
                                            </a>
                                            <a class="dislike" idimage="@image.Id">
                                                <i class="far fa-thumbs-down likedislike"></i>
                                                <i dislikeidimage="@image.Id">@image.DisLike</i>
                                            </a>
                                        </div>
                                    </figcaption>
                                </figure>
                            </div>
                        }
                    }
                </div>
            </div>
        }

    }
</div>

WebGallery/Views/Image/PartialViewGenry.cshtml
@using WebGallery.Models
@model IEnumerable<GenreDisplay>


@foreach (var item in Model)
{
    <li><a href=@Url.HttpRouteUrl("GenreRoute", new { controller = "Image", action = "Index", genre = item.Genre , page = 1 })>@item.Genre</a></li>
}

WebGallery/Views/Image/PartialViewMenu.cshtml
@using WebGallery.Models
@model IEnumerable<GenreDisplay>

<nav class="sideNav">

    <ul>
        @foreach (var item in Model)
        {
            <li><a class="class_of_img" href=@Url.HttpRouteUrl("GenreRoute", new { controller = "Image", action = "Index", genre = item.Genre , page = 1 })>@item.Genre</a><a href="" class="number_of_class_img" idgenry="@item.Genre">@item.NumberOfImages</a> </li>
        }
    </ul>
</nav>

WebGallery/Views/Image/PopularImages.cshtml
@model WebGallery.Models.SortListDisplay

<div class="gallery">
    <div class="images-line">
        <div class="img-rack">
            @{
                foreach (var image in Model.Images)
                {
                    <div class="img-slid" id="@image.Id">
                        <figure>
                            <a href="@Url.Action("Details", "Image", new { id = image.Id })" class="increase_link">
                                <img src="@Url.Content(image.Path)" alt="image_name">
                            </a>
                            <figcaption>
                                <div>@image.Name</div>
                                <div>
                                    <a class="like" idimage="@image.Id">
                                        <i class="far fa-thumbs-up"></i>
                                        <i likeidimage="@image.Id">@image.Like</i>
                                    </a>
                                    <a class="dislike" idimage="@image.Id">
                                        <i class="far fa-thumbs-down"></i>
                                        <i dislikeidimage="@image.Id">@image.DisLike</i>
                                    </a>
                                </div>
                            </figcaption>
                        </figure>
                    </div>
                }
            }
        </div>
        <div>
            @{
                var next = Model.Page.CurrentPage + 1;
                var previous = Model.Page.CurrentPage - 1;
                if (Model.Page.CurrentPage == 1 && Model.Page.TotalPages > 1)
                {
                    <a href="/Image/PopularImages?page=@next" class="toRight">Cледующие</a>
                }
                else if (Model.Page.CurrentPage == Model.Page.TotalPages && Model.Page.TotalPages > 1)
                {
                    <a href="/Image/PopularImages?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                }
                else if (Model.Page.CurrentPage > 1 && Model.Page.CurrentPage < Model.Page.TotalPages)
                {
                    <a href="/Image/PopularImages?page=@previous" class="toLeft">Предыдущие &nbsp;</a>
                    <a href="/Image/PopularImages?page=@next" class="toRight">Cледующие</a>
                }
            }
        </div>
    </div>
</div>

WebGallery/Views/Image/ViewStart.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    Html.RenderAction("PartialViewAll");
}